const {testCountWords} = require('./tests/countWords.js');
const {testFindPattern} = require('./tests/findPattern.js');
const {testHasDigits} = require('./tests/hasDigits.js');
const {testHasLowerCase} = require('./tests/hasLowerCase.js');
const {testHasSpecialChars} = require('./tests/hasSpecialChars.js');
const {testHasUpperCase} = require('./tests/hasUpperCase.js');
const {testIsCreditCard} = require('./tests/isCreditCard.js');
const {testIsDate} = require('./tests/isDate.js');
const {testIsEmail} = require('./tests/isEmail.js');
const {testIsIBAN} = require('./tests/isIBAN.js');
const {testIsIP} = require('./tests/isIP.js');
const {testIsLengthBetween} = require('./tests/isLengthBetween.js');
const {testIsPalindrome} = require('./tests/isPalindrome.js');
const {testIsPhoneNumber} = require('./tests/isPhoneNumber.js');
const {testIsPostalCode} = require('./tests/isPostalCode.js');
const {testIsSSN} = require('./tests/isSSN.js');
const {testIsTime} = require('./tests/isTime.js');
const {testIsURL} = require('./tests/isURL.js');
const {testMatchExact} = require('./tests/matchExact.js');
const {testReplacePattern} = require('./tests/replacePattern.js');

testCountWords();
testFindPattern();
testHasDigits();
testHasLowerCase();
testHasSpecialChars();
testHasUpperCase();
testIsCreditCard();
testIsDate();
testIsEmail();
testIsIBAN();
testIsIP();
testIsLengthBetween();
testIsPalindrome();
testIsPhoneNumber();
testIsPostalCode();
testIsSSN();
testIsTime();
testIsURL();
testMatchExact();
testReplacePattern();